"""Provider-free retrieval behavior and contracts."""

from supp_bro.retrieval.rag import (
    DEFAULT_MIN_VECTOR_SCORE,
    EXPERIMENTS,
    FALLBACK,
    NO_RETRIEVAL_FILTER_SCORE,
    POST_VALIDATOR_MODES,
    PROMPT_FLAVORS,
    RESPONSE_SCHEMA,
    GenerationResult,
    RetrievedChunk,
    accept_payload_without_post_validation,
    best_vector_score,
    build_context_map,
    build_output,
    build_prompt,
    context_is_weak,
    generate,
    markdown_table,
    prompt_template,
    run_experiments,
    summarize_experiment,
    to_rag_observation,
    validate_payload,
    weak_context_reason,
)

__all__ = [
    "DEFAULT_MIN_VECTOR_SCORE",
    "EXPERIMENTS",
    "FALLBACK",
    "NO_RETRIEVAL_FILTER_SCORE",
    "POST_VALIDATOR_MODES",
    "PROMPT_FLAVORS",
    "RESPONSE_SCHEMA",
    "GenerationResult",
    "RetrievedChunk",
    "accept_payload_without_post_validation",
    "best_vector_score",
    "build_context_map",
    "build_output",
    "build_prompt",
    "context_is_weak",
    "generate",
    "markdown_table",
    "prompt_template",
    "run_experiments",
    "summarize_experiment",
    "to_rag_observation",
    "validate_payload",
    "weak_context_reason",
]
